### ISSUE TITLE
Why define Thank words on every message

### ISSUE THREAD

**Issue by MasterBaiter123** [Dhravya/Spacebot#16]
https://github.com/Dhravya/Spacebot/blob/5a3c545fe8faa0fcfa8b301c93feff95494baccf/src/cogs/backgroundtasks.py#L66

IMO, the overall background tasks are a bit too complex. You might wanna split then up into cogs or smth

**Comment by Dhravya** [comment]
Can you please elaborate as to what to split, etc? Thanks for the feedback though, i completely agree

**Comment by MasterBaiter123** [comment]
You could move `thank_words = ["thanks","thank you", "thank"]` outside of the class (somewhere around line 8-9)

Or you could define it as a class attribute. Define it near line 24 outside of the \_\_init\_\_ (single indented) and access it using `self.thank_words`

**Comment by MasterBaiter123** [comment]
You can also use regular expressions to check if the thank words are in the message. 

Splitting the content into words and looping through all of them will put load on the machine if there are long messages. 
And `thank you` will never work as it is 2 words.

**Comment by Necrozma200** [comment]
yes maybe remove 'thank you ' coz "you' will be taken as a member and when it doesnt find it ,it'll throw error

**Comment by MasterBaiter123** [comment]
Yeah but you can use regex instead as it will work on multi-worded string

**Comment by Dhravya** [comment]
Yes thats right. @MasterBaiter123 I noticed that you forked this repository. You're working on #9  Right? maybe you could also try fixing this issue along with it?

**Comment by MasterBaiter123** [comment]
Sure. i'll try

**Comment by Dhravya** [comment]
Thank you !!
