### ISSUE TITLE
Move the `slash_command`s from main.py to the respective cogs

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/Spacebot#2]
Currently, there are a lot of commands in main.py file, that need to be converted into slash cogs. like /help to bot commands, /ban  to moderation, /thank to fun, etc.

**Comment by Dhravya** [comment]
anyone doing this ?

**Comment by kaylebetter** [comment]
I dont think so

**Comment by MasterBaiter123** [comment]
Brief in which cog you want to move each cmd to. I'll do it later once i can

**Comment by Dhravya** [comment]
Done lel
