### ISSUE TITLE
AI command

### ISSUE THREAD

**Issue by ArceusOmkar7** [Dhravya/Spacebot#22]
make something to stop the ai chat, i recommend checking for `if message.content == "stop": #stop the char`

**Comment by Dhravya** [comment]
"Bye" stops AI CHAT doesn't it?

**Comment by ArceusOmkar7** [comment]
> "Bye" stops AI CHAT doesn't it?

ig u should add more of them (stop words) or add a subcommand to stop too...

**Comment by Dhravya** [comment]
Hi can you please suggest more stop words? things like
`bye` `stop` and ?? I cant really think of more
