### ISSUE TITLE
Missing file in kill command

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/Spacebot#26]
![image](https://user-images.githubusercontent.com/63950637/145683768-c9517a45-9c4f-4e27-8cec-b46d004957b0.png)

the error is raised here
https://github.com/Dhravya/Spacebot/blob/fd86a1a97707bc9bcf1b4d8d102c2aec6eca9d8b/src/cogs/images.py#L55

**Comment by MasterBaiter123** [comment]
Ah wrong folder.. I'll fix it

**Comment by MasterBaiter123** [comment]
Wait all the commands in there are using the wrong folder. Do the rest of the commands work?

**Comment by Dhravya** [comment]
> Wait all the commands in there are using the wrong folder. Do the rest of the commands work?

probably not lmfao 💀
