### ISSUE TITLE
Anything that has "ty" in it triggers the +1 reputation

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/Spacebot#35]
words like "party", "shitty" are triggering the reputation. this can probably be fixed by adding spaces `ty [ ]` before and after the thing, not ideal, but i cant think of anything else

**Comment by kaylebetter** [comment]
well can't you just make the reputation thing detect words like `thanks`, `thank you` but not words that have `ty` in them

**Comment by MasterBaiter123** [comment]
Ohh my bad. you have to make regex search for them as words

ill fix that....

**Comment by MasterBaiter123** [comment]
Fixed in #36 
Yet to be tested

**Comment by Dhravya** [comment]
Thank you, I'll merge it and keep this issue open till its tested

**Comment by Dhravya** [comment]
tested, no errors, no reponse
