### ISSUE TITLE
Universal Translate utility

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/Spacebot#42]
Is there a way we can make spacebot so that it automatically detects the language and translate to english?

To take it a step furthur, is there a way to make those "app commands" sort of a thing, but for translate?
![image](https://user-images.githubusercontent.com/63950637/145776722-3eb92e3c-5747-43eb-bf8f-9eff722ff6d1.png)

**Comment by MasterBaiter123** [comment]
https://stackabuse.com/text-translation-with-google-translate-api-in-python/

The google translate api could be used

**Comment by Dhravya** [comment]
Thanks to @MasterBaiter123 This is fixed now. closing
