### ISSUE TITLE
Why don't make a snipe command??

### ISSUE THREAD

**Issue by v1s1t0r999** [Dhravya/Spacebot#56]

**Comment by v1s1t0r999** [comment]
Also just fyi, you can use [discordSuperUtils](https://github.com/discordSuperUtils/discord-super-utils). Its rly good.
And I ain't catfishing too....i have no connections with it....Its just too good and ive used it....so a recommendation

**Comment by v1s1t0r999** [comment]
DAMN!!!!!
I thought it was a small bot. I know discord doesn't allows bots in more than a 100 guilds to save message-context in cache. Its a privileged intent. I thought it was a small bot that could save it 🤦🏻

**Comment by Dhravya** [comment]
Damn, I didn't know about discord super utils, its like spoonfeeding though. 
if other contributors feel like it's a good idea, I'll implement some features for sure

**Comment by Necrozma200** [comment]
ik it , didnt wanna recommend it though
