### ISSUE TITLE
Usage of sqlite

### ISSUE THREAD

**Issue by oliiiiiiiiiiiii** [Dhravya/Spacebot#8]
sqlite is not async and since dpy and its forks are all working in async environments it is recommended to use asiosqlite instead of sqlite

**Comment by Dhravya** [comment]
Thank you for your suggestion.  If you could help me with aiosqlite(i am not familiar with it yet), Please feel free to fork and submit a PR!!

**Comment by oliiiiiiiiiiiii** [comment]
aiosqlite is quite similar to sqlite except most of the functions are coroutines ( you will have to use await while calling them )

**Comment by oliiiiiiiiiiiii** [comment]
you can check their documentation here : https://readthedocs.org/projects/aiosqlite/

**Comment by Dhravya** [comment]
Alright!!! I'll do it. Thanks for the suggestion!
\

**Comment by Dhravya** [comment]
Hi @oliiiiiiiiiiiii , I just realised how much work this issue will take. Every single usage of SQLite will have to be changed. I don't really think its worth doing this right now. However, if you would like to submit a pull request with the implementation, please feel free to. just know that I'll not be working on this issue anytime soon
