### ISSUE TITLE
Usage of Discord-Together

### ISSUE THREAD

**Issue by MasterBaiter123** [Dhravya/Spacebot#9]
From what I briefly checked, you are using Pycord Alpha. Yet you seem to be using Discord-Together for creating Embedded Activity Invites. 

Pycord provides a `channel.create_activity_invite` method on Voice Channels
Usage can be-

```py
channel_invite = await channel.create_activity_invite(application_id) #You can find application ids from the source code of Discord Together. Maybe store and find it from somewhere.
await ctx.send(f"Invite is {channel_invite}")
```

This way, you can rely less on 3rd party libraries that could lead to bugs/errors which are difficult to trace.

**Comment by Dhravya** [comment]
Yes, you are right. I was actually not aware of this ability earlier. Thanks for informing

**Comment by Dhravya** [comment]
Hi @MasterBaiter123 would you like to work on this issue? Just trying to finish up everything as soon as possible, and I'm a bit busy right now (working on https://millenia.tech)
It would be really helpful if you do.

**Comment by MasterBaiter123** [comment]
Hmm. Alright i'll try
